stages:
- test
- dev
- prod

test:
  stage: test
  #only:
  #  - test
  tags:
    - test
  script:
    - hostname

dev:
  stage: dev
  #only:
  #  - test
  tags:
    - dev
  script:
    - hostname

prod:
  stage: prod
  #only:
  #  - test
  tags:
    - prod
  script:
    - hostname