stages:
- test
- dev
- prod

test:
  stage: test
  only:
    - test
  tags:
    - test
  script:
    - pwd
    - mv test.env .env
    - dotnet run

dev:
  stage: dev
  only:
    - dev
  tags:
    - dev
  script:
    - pwd
    - mv dev.env .env
    - dotnet run


prod:
  stage: prod
  only:
    - prod
  tags:
    - prod
  script:
    - pwd
    - dotnet run