stages:
- test
- dev
- prod

test:
  stage: test
  only:
    - test
  tags:
    - test
  script:
    - hostname

dev:
  stage: dev
  only:
    - dev
  tags:
    - dev
  script:
    - hostname

prod:
  stage: prod
  only:
    - prod
  tags:
    - prod
  script:
    - hostname